[pipeline]
id = "fanout-timed"
name = "并行计时演示"
description = ""

[[nodes]]
id = "input"
kind = "builtin"
builtin = "file_input"

[[nodes]]
id = "brA"
kind = "builtin"
builtin = "ffmpeg"
params = { args = ["-i", "{input}", "-vf", "noise=alls=20:allf=t", "-c:v", "libx264", "-preset", "veryslow", "-an", "{output}"], output_extension = "mp4" }

[[nodes]]
id = "brB"
kind = "builtin"
builtin = "ffmpeg"
params = { args = ["-i", "{input}", "-vf", "eq=brightness=-0.1:saturation=2", "-c:v", "libx264", "-preset", "veryslow", "-an", "{output}"], output_extension = "mp4" }

[[nodes]]
id = "merge"
kind = "builtin"
builtin = "ffmpeg"
params = { args = ["-i", "{input.brA}", "-i", "{input.brB}", "-filter_complex", "[0:v][1:v]hstack=inputs=2[v]", "-map", "[v]", "-c:v", "libx264", "-preset", "ultrafast", "{output}"], output_extension = "mp4" }

[[nodes]]
id = "output"
kind = "builtin"
builtin = "file_output"
params = { extension = "mp4" }

[[edges]]
from = ["input", "output"]
to = ["brA", "input"]

[[edges]]
from = ["input", "output"]
to = ["brB", "input"]

[[edges]]
from = ["brA", "output"]
to = ["merge", "input"]

[[edges]]
from = ["brB", "output"]
to = ["merge", "input"]

[[edges]]
from = ["merge", "output"]
to = ["output", "input"]
